### PR TITLE
Add an image that responds to ontario errors

### LINKED ISSUE #124: Handle disconnects on web frontend
The image buffer should de-propagate the node pipeline when a source image has no path to the output. The result would be a blank canvas in the case of just one image source. 

This might actually already work on the backend, but I cannot tell since the image preview does not update upon a disconnect.

### PR DESCRIPTION
**Pull request by notgull**
Closes #124 

image

### CODE REVIEW

**Comment by parkern342** [comment]
This should probably show a error icon rather than a full image. 
image

maybe something like this displayed very small in the center of the screen.

**Comment by notgull** [comment]
Sounds good; if you have an error icon I'll use it.

**Comment by parkern342** [comment]
image
 how about this?

**Comment by notgull** [comment]
Sounds good, here's the new view:

image

**Comment by parkern342** [comment]
Can we center it and make it smaller? The reason is because the icon might be mistaken for something being output.

**Comment by parkern342** [comment]
to be more precise, I'm visualizing it as around 3-4 squares wide on the image grid

**Pull request merged**
